"""API contract models. Source of truth for docs/api-contract.md and
frontend/src/api/types.ts."""

from app.schemas.api import (
    DbConnection,
    DbTableInfo,
    DbTablesRequest,
    DbTablesResponse,
    ErrorResponse,
    FromDbRequest,
    FromDbResponse,
    GenerateRequest,
    GenerateResponse,
    HealthResponse,
    InvoiceListResponse,
    PromptSchemaRequest,
    ProposeScenariosRequest,
    ProposeScenariosResponse,
    SchemaResponse,
    TablePage,
    TemplateSummary,
)
from app.schemas.dataset import (
    ColumnProfile,
    ColumnSchema,
    DatasetSchema,
    DocumentHints,
    ForeignKey,
    InvoiceHints,
    Rule,
    TableSchema,
)
from app.schemas.report import (
    GroundTruthEntry,
    ScenarioProposal,
    ScenarioSelection,
    Similarity,
    ValidationCheck,
    ValidationReport,
)

__all__ = [
    "ColumnProfile",
    "ColumnSchema",
    "DatasetSchema",
    "DbConnection",
    "DbTableInfo",
    "DbTablesRequest",
    "DbTablesResponse",
    "DocumentHints",
    "ErrorResponse",
    "ForeignKey",
    "FromDbRequest",
    "FromDbResponse",
    "GenerateRequest",
    "GenerateResponse",
    "GroundTruthEntry",
    "HealthResponse",
    "InvoiceHints",
    "InvoiceListResponse",
    "PromptSchemaRequest",
    "ProposeScenariosRequest",
    "ProposeScenariosResponse",
    "Rule",
    "ScenarioProposal",
    "ScenarioSelection",
    "SchemaResponse",
    "Similarity",
    "TableSchema",
    "TablePage",
    "TemplateSummary",
    "ValidationCheck",
    "ValidationReport",
]
