import { ChevronDown } from "lucide-react"
import { SectionHeading } from "./SectionHeading"

const QUESTIONS = [
  {
    q: "Does the AI write the data?",
    a: "No. The AI only helps understand your schema and suggest edge cases. Every row is generated by DatDub's engine from rules and statistics, which keeps the data consistent, fast to produce and reproducible.",
  },
  {
    q: "Is my database or file sent to an AI?",
    a: "No. The AI sees column names, types and summary statistics, never raw rows. Databases are opened read-only and sample rows are discarded right after profiling.",
  },
  {
    q: "Can I get exactly the same data again?",
    a: "Yes. Use the same schema, settings and seed and DatDub produces the same dataset. The export page shows everything needed to recreate it.",
  },
  {
    q: "What do I get at the end?",
    a: "Every table as CSV and JSON, the schema, a validation report, an answer key of the edge cases and, for invoice data, PDF invoices, all in one ZIP.",
  },
]

export function Faq() {
  return (
    <section id="faq" aria-labelledby="faq-title" className="w-full scroll-mt-16 border-y border-chrome/60 bg-panel py-14 md:py-16">
      <div className="mx-auto max-w-[760px] px-margin md:px-margin-lg">
        <SectionHeading id="faq-title" title="Questions teams ask first" />
        <div className="mt-8 divide-y divide-line overflow-hidden rounded-xl border border-line bg-card shadow-sm">
          {QUESTIONS.map(({ q, a }) => (
            <details key={q} className="group">
              <summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-6 py-5 font-heading text-headline-sm font-medium text-ink hover:bg-page/60 [&::-webkit-details-marker]:hidden">
                {q}
                <ChevronDown className="size-5 shrink-0 text-ink-muted transition-transform group-open:rotate-180" aria-hidden="true" />
              </summary>
              <p className="px-6 pb-5 text-body-md text-ink-muted">{a}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  )
}
