import { Clock, DatabaseZap, EyeOff, UserRoundX, type LucideIcon } from "lucide-react"

const POINTS: { icon: LucideIcon; title: string; body: string }[] = [
  {
    icon: EyeOff,
    title: "The AI never sees your rows",
    body: "It works from column names, types and summary statistics. Every row is generated by DatDub's own engine.",
  },
  {
    icon: DatabaseZap,
    title: "Read-only by design",
    body: "Databases are opened in a read-only transaction. Sample rows are profiled in memory, then discarded.",
  },
  {
    icon: UserRoundX,
    title: "Personal data is replaced",
    body: "Names, emails, phones and addresses are always new fake values, never copied from your source.",
  },
  {
    icon: Clock,
    title: "Deleted after 60 minutes",
    body: "No accounts and no stored projects. Generated datasets expire automatically.",
  },
]

/** Trust section: same colours as the rest of the page, a two-column layout to set it apart. */
export function PrivacyBand() {
  return (
    <section id="privacy" aria-labelledby="privacy-title" className="w-full scroll-mt-16 py-14 md:py-16">
      <div className="mx-auto grid max-w-[1100px] items-center gap-10 px-margin md:px-margin-lg lg:grid-cols-[minmax(0,5fr)_minmax(0,7fr)]">
        <div>
          <p className="mb-3 inline-flex rounded-full bg-primary-tint px-3 py-1 font-heading text-label-md font-medium text-primary-deep">
            Privacy
          </p>
          <h2 id="privacy-title" className="font-heading text-headline-lg font-medium tracking-tight text-ink md:text-headline-xl">
            Safe to use with real systems
          </h2>
          <p className="mt-3 max-w-md text-body-lg text-ink-muted">
            Point DatDub at a real database or real files. Your rows never go to an AI and are never stored.
          </p>
        </div>
        <ul className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {POINTS.map(({ icon: Icon, title, body }) => (
            <li key={title} className="rounded-xl border border-line bg-card p-5 shadow-sm">
              <div className="flex items-center gap-3">
                <span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-primary-tint text-primary-deep">
                  <Icon className="size-[18px]" aria-hidden="true" />
                </span>
                <h3 className="font-heading text-headline-sm font-medium text-ink">{title}</h3>
              </div>
              <p className="mt-3 text-body-md text-ink-muted">{body}</p>
            </li>
          ))}
        </ul>
      </div>
    </section>
  )
}
