import { ArrowRight, Clock, Database, DatabaseZap, EyeOff, Sparkles, UserRoundX, Workflow, type LucideIcon } from "lucide-react"
import { SectionHeading } from "./SectionHeading"

/** Where each kind of information goes, left to right. */
const FLOW: { icon: LucideIcon; title: string; keeps: string[] }[] = [
  { icon: Database, title: "Your source", keeps: ["Real rows stay here", "Opened read-only", "Credentials used once"] },
  { icon: Workflow, title: "DatDub engine", keeps: ["Profiles a small sample", "Keeps it in memory only", "Writes every new row"] },
  { icon: Sparkles, title: "AI model", keeps: ["Column names and types", "Summary statistics", "Never a single row"] },
]

const POINTS: { icon: LucideIcon; title: string; body: string }[] = [
  {
    icon: EyeOff,
    title: "The AI never sees your rows",
    body: "It works from column names, types and summary statistics. Every row is generated by DatDub's own engine.",
  },
  {
    icon: DatabaseZap,
    title: "Read-only by design",
    body: "Databases are opened in a read-only transaction. Sample rows are profiled in memory, then discarded.",
  },
  {
    icon: UserRoundX,
    title: "Personal data is replaced",
    body: "Names, emails, phones and addresses are always new fake values, never copied from your source.",
  },
  {
    icon: Clock,
    title: "Deleted after 60 minutes",
    body: "No accounts and no stored projects. Generated datasets expire automatically.",
  },
]

export function PrivacyBand() {
  return (
    <section
      id="privacy"
      aria-labelledby="privacy-title"
      className="w-full scroll-mt-16 py-20 md:py-24"
    >
      <div className="mx-auto max-w-[1160px] px-margin md:px-margin-lg">
        <SectionHeading
          id="privacy-title"
          title="How we keep you secure"
          subtitle="Point DatDub at a real database or real files. Here is exactly what goes where."
        />

        {/* Data flow: what each stage is allowed to see. */}
        <ol aria-label="Where your data goes" className="mt-10 grid grid-cols-1 items-stretch gap-3 md:grid-cols-[1fr_auto_1fr_auto_1fr]">
          {FLOW.map(({ icon: Icon, title, keeps }, i) => (
            <li key={title} className="contents">
              {i > 0 && (
                <span aria-hidden="true" className="flex items-center justify-center text-hint">
                  <ArrowRight className="size-5 rotate-90 md:rotate-0" />
                </span>
              )}
              <div
                className={
                  i === 2
                    ? "rounded-2xl border border-primary/30 bg-primary-tint/50 p-5"
                    : "rounded-2xl border border-line bg-card p-5"
                }
              >
                <div className="flex items-center gap-3">
                  <span className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
                    <Icon className="size-[18px]" aria-hidden="true" />
                  </span>
                  <h3 className="font-heading text-headline-sm font-medium text-ink">{title}</h3>
                </div>
                <ul className="mt-4 space-y-1.5 text-body-md text-ink-muted">
                  {keeps.map((k) => (
                    <li key={k} className="flex items-center gap-2">
                      <span className="size-1.5 shrink-0 rounded-full bg-primary" aria-hidden="true" />
                      {k}
                    </li>
                  ))}
                </ul>
              </div>
            </li>
          ))}
        </ol>

        <ul className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {POINTS.map(({ icon: Icon, title, body }) => (
            <li key={title} className="rounded-2xl border border-line bg-card p-5 shadow-sm">
              <span className="flex size-9 items-center justify-center rounded-lg bg-primary-tint text-primary-deep">
                <Icon className="size-[18px]" aria-hidden="true" />
              </span>
              <h3 className="mt-4 font-heading text-headline-sm font-medium text-ink">{title}</h3>
              <p className="mt-2 text-body-md text-ink-muted">{body}</p>
            </li>
          ))}
        </ul>
      </div>
    </section>
  )
}
